name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sub-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Notify on Telegram
        run: |
          TIMESTAMP=$(TZ=Asia/Manila date +"%Y-%m-%d %H:%M:%S %Z %z")
          
          MESSAGE="🚀 GitHub Action triggered%0A"
          MESSAGE+="📦 Repository: ${{ github.repository }}%0A"
          MESSAGE+="🌱 Branch: ${{ github.ref }}%0A"
          MESSAGE+="🕒 Triggered at: ${TIMESTAMP}"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=${MESSAGE}"

      - name: Build and Push Image
        run: |
          docker buildx build --platform linux/amd64 \
          -t ghcr.io/${{ github.actor }}/docker-peer2profit:latest --push .
